#!/bin/bash

# This script generates the default certificates. It only needs to be run it changes
# are made to this script; otherwise everything's already in the git repo.

mydir=$(cd `dirname $0`;pwd)
cwd=$(pwd)

mkdir -p ${mydir}/install.server/etc/ssl/rsyslog

# Make self-signed CA cert and key
openssl req -x509 -newkey rsa:2048 -keyout ${mydir}/install.server/etc/ssl/rsyslog/rsyslog-ca.key -out ${mydir}/install.server/etc/ssl/rsyslog/rsyslog-ca.crt -days 9999 -nodes -subj "/CN=rsyslog-server.clearwater.metaswitch.comm"
chmod 0400 ${mydir}/install.server/etc/ssl/rsyslog/rsyslog-ca.*
openssl x509 -serial -in ${mydir}/install.server/etc/ssl/rsyslog/rsyslog-ca.crt -noout -text

# Make server csr and key
openssl req -new -newkey rsa:2048 -keyout ${mydir}/install.server/etc/ssl/rsyslog/rsyslog-server.key -out ${mydir}/install.server/etc/ssl/rsyslog/rsyslog-server.csr -subj "/CN=rsyslog-server.clearwater.metaswitch.comm" -nodes
chmod 0400 ${mydir}/install.server/etc/ssl/rsyslog/rsyslog-server.key

# Make the server's cert
openssl x509 -req -days 9999 -in ${mydir}/install.server/etc/ssl/rsyslog/rsyslog-server.csr -CA ${mydir}/install.server/etc/ssl/rsyslog/rsyslog-ca.crt -CAkey ${mydir}/install.server/etc/ssl/rsyslog/rsyslog-ca.key -out ${mydir}/install.server/etc/ssl/rsyslog/rsyslog-server.crt -set_serial 1
chmod 0400 ${mydir}/install.server/etc/ssl/rsyslog/rsyslog-server.crt
openssl x509 -serial -in ${mydir}/install.server/etc/ssl/rsyslog/rsyslog-server.crt -noout -text

# Make client csr and key
openssl req -new -newkey rsa:2048 -keyout ${mydir}/install.server/etc/ssl/rsyslog/rsyslog-client.key -out ${mydir}/install.server/etc/ssl/rsyslog/rsyslog-client.csr -subj "/CN=rsyslog-client.clearwater.metaswitch.com" -nodes
chmod 0400 ${mydir}/install.server/etc/ssl/rsyslog/rsyslog-client.key

# Make the client's cert
openssl x509 -req -days 9999 -in ${mydir}/install.server/etc/ssl/rsyslog/rsyslog-client.csr -CA ${mydir}/install.server/etc/ssl/rsyslog/rsyslog-ca.crt -CAkey ${mydir}/install.server/etc/ssl/rsyslog/rsyslog-ca.key -out ${mydir}/install.server/etc/ssl/rsyslog/rsyslog-client.crt -set_serial 2
chmod 0400 ${mydir}/install.server/etc/ssl/rsyslog/rsyslog-client.crt
openssl x509 -serial -in ${mydir}/install.server/etc/ssl/rsyslog/rsyslog-client.crt -noout -text

cp -vp ${mydir}/install.server/etc/ssl/rsyslog/rsyslog-client.crt ${mydir}/install.server/etc/ssl/rsyslog/rsyslog-client.key ${mydir}/install.server/etc/ssl/rsyslog/rsyslog-ca.crt ${mydir}/install.client/etc/clearwater/ent

(cd ${mydir}/install.server/; tar cvzf ../ent-rsl-server.tgz .)

cat > /tmp/$$.extract <<'EOF'
#!/bin/bash
if [[ $EUID -ne 0 ]]; then
  echo "You must run this script with root permissions"
  exit 1
fi
echo "Extracting Clearwater ENT rsyslog server configuration into root(/):"
# searches for the line number where finish the script and start the tar.gz
SKIP=`awk '/^__TARFILE_FOLLOWS__/ { print NR + 1; exit 0; }' $0`
#remember our file name
THIS=$0
# take the tarfile and pipe it into tar
tail -n +$SKIP $THIS | tar -vxz -C / | sed -e 's#^#  #'
# Any script here will happen after the tar file extract.
echo "Finished"
stop rsyslog
start rsyslog
exit 0
# NOTE: Don't place any newline characters after the last line below.
__TARFILE_FOLLOWS__
EOF

cat /tmp/$$.extract ${mydir}/ent-rsl-server.tgz > ${mydir}/ent-rsl-server-install.sh
rm -f /tmp/$$.extract
