#!/bin/bash

exec >  >( stdbuf -i0 -o0 -e0 tee /var/log/clearwater-cleanup.log )
exec 2>&1

set +e

echo /usr/bin/clearwater-cleandir /var/log /var/clearwater-diags-monitor/dumps --limit 10% --before now
/usr/bin/clearwater-cleandir /var/log /var/clearwater-diags-monitor/dumps --limit 10% --before now

exec 1>&-
exit 0
