#!/bin/bash

exec >/var/log/clearwater-cleanup.log

set +e

command='/usr/bin/clearwater-cleandir /var/log /var/clearwater-diags-monitor/dumps --limit 10% --before now'
echo "$command"
$command

exit 0
