#!/bin/sh

# dhclient change hostname script for Ubuntu
# /etc/dhcp/dhclient-exit-hooks.d/sethostname
# logs in /var/log/upstart/network-interface-eth0.log

# for debugging:
echo "sethostname BEGIN"
export
set -x

intf=${interface}-ipv4
if [ ! -z "${new_ip6_address}" ]; then
    intf=${interface}-ipv6
fi
rm -f /tmp/dhcp.${intf}.env

if [[ "$reason" = "BOUND" || "$reason" = "REBOOT" || "$reason" = "TIMEOUT" ]]; then
    export > /tmp/dhcp.${intf}.env

    echo new_ip_address=$new_ip_address
    echo new_host_name=$new_host_name
    echo new_domain_name=$new_domain_name

    oldhostname=$(hostname)
    if [ "$oldhostname" != "$new_host_name.$new_domain_name" ]; then
        # Rename Host
        echo $new_host_name.$new_domain_name > /etc/hostname
        hostname -F /etc/hostname
	hostname

        # Update /etc/hosts if needed
        TMPHOSTS=/etc/hosts.dhcp.new
        grep -v '127[.]0[.]1[.]1[[:space:]]' < /etc/hosts > $TMPHOSTS
        mv $TMPHOSTS /etc/hosts

        # Recreate SSH2 keys
        export DEBIAN_FRONTEND=noninteractive
        dpkg-reconfigure openssh-server
    fi
else
    if [[ "$reason" = "BOUND6" ]]; then
	export > /tmp/dhcp.${intf}.env
    fi
fi

echo "sethostname END"
